import os
import tempfile
import pytest

from app.core.exporter import (
    export_project_data,
    generate_tree_markdown,
    generate_full_markdown,
    _get_markdown_language,
    _looks_binary,
    sanitize_content,
    MAX_FILE_SIZE_BYTES,
)


def test_language_detection():
    assert _get_markdown_language("main.py") == "python"
    assert _get_markdown_language("App.tsx") == "tsx"
    assert _get_markdown_language("styles.css") == "css"
    assert _get_markdown_language("config.yaml") == "yaml"
    assert _get_markdown_language("Dockerfile") == "dockerfile"
    assert _get_markdown_language("app.dockerfile") == "dockerfile"
    assert _get_markdown_language(".gitignore") == "gitignore"
    assert _get_markdown_language("unknown_file.xyz123") == "text"


def test_binary_detection():
    assert _looks_binary("image.png") is True
    assert _looks_binary("program.exe") is True
    assert _looks_binary("archive.zip") is True
    assert _looks_binary("icon.ico") is True

    with tempfile.NamedTemporaryFile(suffix=".txt", delete=False) as f:
        f.write(b"Normal text content")
        txt_path = f.name

    with tempfile.NamedTemporaryFile(suffix=".txt", delete=False) as f:
        f.write(b"Binary \x00 with null bytes")
        bin_path = f.name

    try:
        assert _looks_binary(txt_path) is False
        assert _looks_binary(bin_path) is True
    finally:
        os.remove(txt_path)
        os.remove(bin_path)


def test_sensitive_content_sanitization():
    raw = 'api_key = "sk-1234567890abcdef"\npassword = \'my_secret_pass\''
    sanitized = sanitize_content(raw)
    assert "sk-1234567890abcdef" not in sanitized
    assert "my_secret_pass" not in sanitized
    assert "REDACTED SENSITIVE VALUE" in sanitized


def test_markdown_exports_both_modes():
    with tempfile.TemporaryDirectory() as temp_dir:
        # Create dummy project structure
        src_dir = os.path.join(temp_dir, "project_src")
        export_target = os.path.join(temp_dir, "out")
        os.makedirs(src_dir)
        os.makedirs(export_target)

        file_py = os.path.join(src_dir, "app.py")
        with open(file_py, "w", encoding="utf-8") as f:
            f.write("def run():\n    print('ContextPot')\n")

        file_bin = os.path.join(src_dir, "image.png")
        with open(file_bin, "wb") as f:
            f.write(b"\x89PNG\r\n\x1a\n\x00\x00\x00")

        mock_data = {
            "name": "ProjectDemo",
            "path": "",
            "abs_path": src_dir,
            "type": "folder",
            "children": [
                {
                    "name": "app.py",
                    "path": "app.py",
                    "abs_path": file_py,
                    "type": "file",
                },
                {
                    "name": "image.png",
                    "path": "image.png",
                    "abs_path": file_bin,
                    "type": "file",
                }
            ]
        }

        # 1. Test Tree only export
        tree_files = export_project_data(mock_data, export_target, mode="Tree only")
        assert len(tree_files) == 1
        assert tree_files[0].endswith("ProjectDemo_tree.md")
        assert os.path.isfile(tree_files[0])

        with open(tree_files[0], "r", encoding="utf-8") as f:
            tree_text = f.read()
        assert "# ProjectDemo" in tree_text
        assert "> Generated by ContextPot" in tree_text
        assert "```text" in tree_text
        assert "📁 ProjectDemo/" in tree_text
        assert "## Code & File Contents" not in tree_text

        # 2. Test Whole code + Tree export
        full_files = export_project_data(mock_data, export_target, mode="Whole code + Tree")
        assert len(full_files) == 1
        assert full_files[0].endswith("ProjectDemo_full.md")
        assert os.path.isfile(full_files[0])

        with open(full_files[0], "r", encoding="utf-8") as f:
            full_text = f.read()
        assert "# ProjectDemo" in full_text
        assert "## Code & File Contents" in full_text
        assert "### app.py" in full_text
        assert "```python" in full_text
        assert "def run():" in full_text
        assert "### image.png" in full_text
        assert "Binary file excluded from text export" in full_text


def test_ignore_patterns_and_exclusions():
    from app.core.ignore_manager import get_ignore_manager
    mgr = get_ignore_manager()

    # 1. Pattern .svg matching
    mgr.user_patterns = [".svg"]
    mgr.removed_defaults = set()
    mgr.session_patterns = []
    mgr._invalidate_matchers()

    assert mgr.should_ignore_export("app_logo.svg") is True
    assert mgr.should_ignore_export("assets/app_logo.svg") is True
    assert mgr.should_ignore_export(r"X:\Project\assets\app_logo.svg") is True
    assert mgr.should_ignore_export("assets/Files Icon/3d.svg") is True
    assert mgr.should_ignore_export("main.py") is False

    # 2. Session exclusion
    mgr.add_session_pattern("main.py")
    assert mgr.should_ignore_export("main.py") is True

    # 3. Folder exclusion
    mgr.add_session_pattern("Files Icon")
    assert mgr.should_ignore_export("Files Icon") is True
    assert mgr.should_ignore_export("assets/Files Icon/custom.svg") is True

    mgr.clear_session_patterns()
